### ISSUE TITLE
关于代码运行方面的一些问题

### ISSUE THREAD

**Issue by 18456432930** [KyleZheng1997/ReSSL#2]
你好，我只有一块GPU，我应该输入什么语句去跑你的代码？我发现有一个ressl_multi.py和一个ressl.py文件，请问这两个有什么区别吗？是一个为单GPU准备的，一个为多GPU准备的代码吗？

**Comment by KyleZheng1997** [comment]
The difference between ressl_multi.py and ressl.py is that the former one adopts 5 positive crops and the latter adopts 1 positive crop.

Since we adopt the ImageNet1k as our default dataset, so I think there is no way to run this code with only one GPU.

If you want to test ReSSL on a smaller dataset, I recommend you follow the official MoCo implementation for cifar10 in [MoCo-cifar10](https://colab.research.google.com/github/facebookresearch/moco/blob/colab-notebook/colab/moco_cifar10_demo.ipynb#scrollTo=lzFyFnhbk8hj), and then replace the contrastive loss with our proposed relational consistency loss.

**Comment by 18456432930** [comment]
但是你给的链接也是在多GPU上使用的，你有什么更好的解决办法，比如在你现有的代码上进行修改

**Comment by 18456432930** [comment]
你有什么更好的方法吗？比如直接在你的代码上进行修改哪一部分

**Comment by KyleZheng1997** [comment]
Nope, directly change the loss function in [MoCo-cifar10](https://colab.research.google.com/github/facebookresearch/moco/blob/colab-notebook/colab/moco_cifar10_demo.ipynb#scrollTo=lzFyFnhbk8hj) should be much easier than modify this codebase.
